minikube_driver: docker
minikube_memory: "2800"
minikube_cpus: "2"
minikube_profile: "minikube"
minikube_k8s_version: "stable"
minikube_proxy_port: 8001
minikube_run_user: "minikube"
minikube_base_image: "gcr.io/k8s-minikube/kicbase-builds:v0.0.50-1772266598-22719@sha256:9a1ee811971b9b5e9be1b04408ba2b2ce6fd696483ebc1d8085aa2f1561f1ead"