name: Task1 Terraform Destroy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  destroy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: task1/infra

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init -backend-config=backend.hcl

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=destroyplan

      - name: Terraform Destroy
        run: terraform apply -auto-approve destroyplan
