name: Task1 Terraform Destroy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: task1/infra

    env:
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      SPACES_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
      SPACES_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Prepare backend config
        run: |
          cp backend.hcl backend.auto.hcl
          sed -i "s|REPLACE_IN_CI|${SPACES_ACCESS_KEY_ID}|1" backend.auto.hcl
          sed -i "s|REPLACE_IN_CI|${SPACES_SECRET_ACCESS_KEY}|1" backend.auto.hcl

      - name: Terraform Init
        run: terraform init -backend-config=backend.auto.hcl

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -input=false -out=destroyplan

      - name: Terraform Destroy
        run: terraform apply -input=false -auto-approve destroyplan